# Generated by Django 5.2.17 on 2026-09-11 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(db_index=True, max_length=80)),
                ('model', models.CharField(db_index=True, max_length=100)),
                ('year', models.PositiveIntegerField(db_index=True)),
                ('price', models.DecimalField(db_index=True, decimal_places=2, help_text='Price in Nigerian Naira (₦)', max_digits=14)),
                ('mileage', models.PositiveIntegerField(db_index=True, help_text='Mileage in Kilometers (km)')),
                ('condition', models.CharField(choices=[('foreign_used', 'Foreign Used (Tokunbo)'), ('nigerian_used', 'Nigerian Used'), ('brand_new', 'Brand New')], db_index=True, default='foreign_used', max_length=30)),
                ('transmission', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual'), ('cvt', 'CVT'), ('other', 'Other')], db_index=True, default='automatic', max_length=30)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('electric', 'Electric')], db_index=True, default='petrol', max_length=30)),
                ('body_type', models.CharField(choices=[('suv', 'SUV'), ('sedan', 'Sedan'), ('coupe', 'Coupe'), ('pickup', 'Pickup Truck'), ('hatchback', 'Hatchback'), ('convertible', 'Convertible'), ('van', 'Van / Minivan'), ('wagon', 'Station Wagon')], db_index=True, default='suv', max_length=30)),
                ('engine', models.CharField(default='3.5L V6', help_text='e.g. 2.5L 4-Cylinder, 3.5L V6, 5.7L V8', max_length=100)),
                ('exterior_color', models.CharField(default='Black', max_length=60)),
                ('interior_color', models.CharField(default='Black Leather', max_length=60)),
                ('location', models.CharField(db_index=True, default='Lekki, Lagos', max_length=120)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold')], db_index=True, default='available', max_length=20)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('description', models.TextField(blank=True)),
                ('vin', models.CharField(blank=True, max_length=50, verbose_name='VIN / Chassis No')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon_name', models.CharField(blank=True, help_text='Optional icon class', max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/%Y/%m/')),
                ('is_cover', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('caption', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cars.car')),
            ],
            options={
                'ordering': ['-is_cover', 'order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='car',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='cars', to='cars.feature'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['make', 'model'], name='cars_car_make_3ceb9a_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['status', 'is_active'], name='cars_car_status_5f12d3_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['price', 'year'], name='cars_car_price_0cbcc7_idx'),
        ),
    ]
