# Generated by Django 5.2.17 on 2026-09-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Samko Cars', max_length=100)),
                ('tagline', models.CharField(default="Nigeria's Premier Verified Automobile Marketplace", max_length=255)),
                ('phone', models.CharField(default='+234 802 345 6789', max_length=50)),
                ('whatsapp_number', models.CharField(default='2348023456789', help_text='Format with country code without plus sign (e.g. 2348023456789)', max_length=30)),
                ('whatsapp_default_message', models.TextField(default='Hello Samko Cars, I am interested in inquiring about vehicles on your website.')),
                ('email', models.EmailField(default='sales@samkocars.com', max_length=254)),
                ('address', models.CharField(default='Plot 14, Admiralty Way, Lekki Phase 1, Lagos, Nigeria', max_length=255)),
                ('city', models.CharField(default='Lagos, Nigeria', max_length=100)),
                ('opening_hours', models.CharField(default='Mon - Fri: 8:00 AM - 6:00 PM | Sat: 9:00 AM - 5:00 PM | Sun: Closed', max_length=255)),
                ('hero_title', models.CharField(default='Find Your Next Dream Car in Nigeria', max_length=200)),
                ('hero_subtitle', models.TextField(default='Explore our carefully curated selection of inspected Tokunbo, clean Nigerian-used, and brand-new cars with transparent pricing in Naira.')),
                ('about_story', models.TextField(default="Established with a vision for transparency, Samko Cars has evolved into one of Nigeria's most trusted automobile dealerships. We bridge the gap between discerning car buyers and premium, verified vehicles across Lagos, Abuja, and all 36 states.")),
                ('mission', models.TextField(default='To deliver unmatched automotive satisfaction through strict 150-point vehicle inspections, upfront pricing, and frictionless dealership support.')),
                ('vision', models.TextField(default="To be West Africa's leading benchmark in certified pre-owned and luxury automobile sales.")),
                ('quality_assurance', models.TextField(default='Every single vehicle on our lot undergoes an extensive computer diagnostic scan, flood damage inspection, chassis alignment audit, and customs clearance authentication.')),
                ('footer_text', models.TextField(default='Samko Cars is a licensed dealership registered with the Corporate Affairs Commission (CAC) of Nigeria. Delivering automotive excellence and customer integrity.')),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('twitter', 'X (Twitter)'), ('youtube', 'YouTube'), ('linkedin', 'LinkedIn'), ('whatsapp', 'WhatsApp Channel'), ('other', 'Other Platform')], default='instagram', max_length=50)),
                ('platform_name', models.CharField(blank=True, help_text="Custom name if 'Other' selected", max_length=100)),
                ('url', models.URLField()),
                ('icon_class', models.CharField(blank=True, help_text='Optional icon identifier or SVG code', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Social Media Link',
                'verbose_name_plural': 'Social Media Links',
                'ordering': ['order', 'platform'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('location', models.CharField(default='Lekki, Lagos', max_length=120)),
                ('vehicle_purchased', models.CharField(default='2021 Lexus RX 350', max_length=150)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('comment', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
