# Generated by Django 5.2.17 on 2026-09-11 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=120)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=30)),
                ('price_at_request', models.DecimalField(decimal_places=2, help_text='Snapshot of the car price at the time request was made', max_digits=14)),
                ('preferred_inspection_date', models.DateField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New Request'), ('contacted', 'Customer Contacted'), ('processing', 'Inspection Scheduled / Processing'), ('completed', 'Deal Completed / Sold'), ('cancelled', 'Request Cancelled')], db_index=True, default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to='cars.car')),
            ],
            options={
                'verbose_name': 'Purchase / Inspection Request',
                'verbose_name_plural': 'Purchase / Inspection Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
